name       : libuuid
version    : 1.0.3
release    : 2
source     :
    - http://freefr.dl.sourceforge.net/project/libuuid/libuuid-1.0.3.tar.gz : 46af3275291091009ad7f1b899de3d0cea0252737550e7919d17237997db5644
license    : BSD-3-Clause
component  : programming
summary    : Portable uuid C library
description: |
    Portable uuid C library
patterns   :
    - devel:
        - /usr/share/docs/libuuid/stub-devel
install    : |
    echo "Stub, this package needs to be deleted." > stub
    install -Dm00644 stub $installdir/usr/share/docs/libuuid/stub
    install -Dm00644 stub $installdir/usr/share/docs/libuuid/stub-devel
